### PR TITLE
Color filter

### PR DESCRIPTION
**Pull request by emberian**
The regex filter you were talking about, it strips all colors.

### CODE REVIEW

**Comment by amcgregor** [comment]
This pull request won't be accepted in its current form for two reasons: splitting apart the common base code, while generally a good idea, is unfortunate in the context of these Git hooks.  Where should Python look when importing?  Second, you don't detect colourfulness using an environment variable, you detect if the existing stdout "isatty".  If it's a TTY, we're running interactively, otherwise we're part of a pipeline and should not colour output.

**Comment by emberian** [comment]
> Where should Python look when importing? 

Good question. That /could/ be solved with a little shell script (in place of the current hooks) that sets up the path and then loads the module in question. Not great, but it's better than duplicating code everywhere, right? (Those shell scripts could even be symlinks to the same one that simple looks at $0, which is handy). Yes/No?

> you don't detect colourfulness using an environment variable

Yes I do? https://github.com/cmr/snippits/blob/color-filter/core_runner.py#L28

Or are you saying that's not how it should be done? Currently I'm doing both, although you can't force colors if stdout isn't a TTY. I'll push a fix for that when I get home. Often I _want_ to force colors, such as when piping to less or similar. Now, it's unlikely that that case would occur with a commit hook, but it annoys me when a piece of software doesn't support that.

**Comment by emberian** [comment]
Bump

**Comment by amcgregor** [comment]
And yeah, running the hook outside of a commit is unsupported; it _is_ a commit hook after all.  ;P  At this point the code looks acceptable, though the modification to use marrow.util.convert's boolean function (copypasta of that isolated function is A-OK, MIT code and all) is an optional niceness.  I'll give it 24h for my brain to idly context switch and mull it over, then I'll merge.

**Comment by amcgregor** [comment]
Performing an `exec(open(path.join(open(dirname(sys.argv[0]), "common.py")), 'r').read())` (or actually tested variation of that) to include the common code might just work.

**Comment by emberian** [comment]
Bump

**Pull request closed without merging**
